debug = false
loglevel = "ERROR" 

# defaultEntryPoints must be at the top because it should not be in any table below
defaultEntryPoints = ["http", "https"]

[web]
# Port for the status page
address = ":8080"

# Entrypoints, http and https
[entryPoints]

# http should be redirected to https
[entryPoints.http]
address = ":80"

[entryPoints.http.redirect]
entryPoint = "https"

# https is the default
[entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]

[entryPoints.traefik]
    address = ":8080"

[api]
  entryPoint = "traefik"

[retry]    

# Enable ACME (Let's Encrypt): automatic SSL
[acme]
    email = "kuznetsov.daniil.d2@gmail.com"
    storage = "/etc/traefik/acme/acme.json"   
    onHostRule = true
    entryPoint = "https"
    
    [acme.dnsChallenge]
        provider = "digitalocean"
        delayBeforeCheck = 0
    [[acme.domains]]
        main = "*.d2one.ru"
        sans = ["d2one.ru"]

[docker]
    endpoint = "unix:///var/run/docker.sock"
    domain = "d2one.ru"
    watch = true
    exposedbydefault = false